name: job-matcher-phobert-api
services:
- name: web
  source_dir: /
  github:
    repo: dige04/job-matcher-phobert-api
    branch: main
  run_command: uvicorn app:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8080
  routes:
  - path: /